public class louisvilleTileConstants {
	
    public static final String LEAD_LINKS = 'Lead Links';
    public static final String OPPORTUNITY_LINKS = 'Opportunity Links';
    public static final String WON_OPPORTUNITY_LINKS = 'Won Opportunity Links';
    public static final String ORDER_LINKS = 'Order';
    public static final String Marketing = 'Marketing';
    public static final String oppYTD = 'All Opportunities in YTD';
    
    public static final String oppMTD = 'All Opportunities in MTD';
    public static final String accountInYTD = 'All Account in YTD';
    public static final String accountInMTD = 'All Account in MTD';
    public static final String contactYTD = 'All Contacts in YTD';
    public static final String contactMTD = 'All Contacts in MTD';
    public static final String leadYTD = 'All Lead in YTD';
    public static final String leadMTD = 'All Lead in MTD';
}