public class MonthlyBreakdownSelector {
    public static List<monthly_breakdown__c> getMonthlyBreakDownByMonthlyCommission(set<id> monthlyCommissions){
        return [SELECT Id, Name, Account__c, Opportunity__c, Tile_Margin_Percentage__c,
                monthly_commission__r.employee__r.profile.name,
                Ancillary_Margin_Percentage__c, Commission_Split_Percentage__c, Total_Invoice_Tile_Margin__c,Tile_margin__c, 
                Total_Invoice_Ancillary_Margin__c, Total_Margin__c, Met_Margin__c,Elgible_Amount__c,Ancillary_Margin__c,
                Monthly_Commission__c ,tile_sale__c, ancillary_sale__c,Monthly_Commission__r.Name,
                Monthly_Commission__r.Employee__c,Monthly_Commission__r.EoY_Sales_Commission__r.Commission_Master__c FROM Monthly_Breakdown__c 
                WHERE Monthly_Commission__c in : monthlyCommissions];
    }
}